---

- hosts: all
  become: true
  tasks:

  - name: Update repository index
    apt:
      update_cache: yes
  
  - name: Install apache2 package
    apt:
      name: apache2

  - name: Make sure the current version of ‘sysstat’ is installed.
    dnf:
      name: sysstat
      state: latest
